name: Build native release on tag
on:
  push:
    tags:
      - '*'
jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 11

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Execute Gradle build
      run: ./gradlew nativeBinaries

    - name: Archive build
      uses: actions/upload-artifact@v2
      with:
        name: build_${{ runner.os }}
        path: build/bin/native/hcReleaseExecutable/